# NumPy

NumPy es una biblioteca de Python ampliamente utilizada en el campo de la física computacional debido a su capacidad para manejar eficientemente matrices y arreglos multidimensionales. 


NumPy, que significa "Numerical Python", es una biblioteca fundamental para la computación científica en Python. Proporciona un poderoso objeto de matriz multidimensional llamado `ndarray`, junto con una amplia gama de funciones para operar en estas matrices. Las principales características de NumPy incluyen:

- **ndarray**: Un objeto de matriz multidimensional que permite almacenar datos de manera eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para operar en matrices, incluidas las funciones trigonométricas, exponenciales y de álgebra lineal.
- **Operaciones de matriz**: Permite realizar operaciones matriciales eficientes, como multiplicación de matrices, inversión de matrices y descomposición de valores singulares.
- **Indexación y segmentación avanzadas**: Facilita la selección y manipulación de elementos individuales o subconjuntos de una matriz.
- **Integración con otras bibliotecas**: NumPy se integra estrechamente con otras bibliotecas de Python, como SciPy, Matplotlib y pandas, para realizar análisis de datos y visualización.

NumPy es ampliamente utilizado en la física computacional para resolver problemas que implican cálculos numéricos y simulaciones. Algunas aplicaciones comunes incluyen:

- Simulación de sistemas físicos: Utilizar NumPy para simular el comportamiento de sistemas físicos mediante la resolución de ecuaciones diferenciales.
- Análisis de datos experimentales: Utilizar NumPy para procesar y analizar datos experimentales, como mediciones de laboratorio o resultados de simulaciones numéricas.
- Visualización de resultados: Utilizar bibliotecas como Matplotlib junto con NumPy para visualizar los resultados de simulaciones físicas de manera clara y comprensible.

**IMPORTANTE** Al igual que con las listas, las operaciones de asignación entre arrays (=) **no** crean un nuevo objeto, sino tan sólo un nuevo puntero (*handle*) que apunta a la misma dirección de la memoria. Por lo tanto, los cambios que le ocurran a la nueva variable se propagarán a la primera, y viceversa. Para evitarlo, usaremos el método array.copy().

In [4]:
import numpy
numpy.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
import numpy as np


In [6]:
###from numpy import *

In [7]:
linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,10]])
print(array_2d)

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9, 10])]


C:\Users\apmil\AppData\Local\Temp\ipykernel_9540\133164215.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,10]])


In [12]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
# Podemos ver el tamaño de un array con el método shape:
print(array_3d.shape)

(2, 2, 3)


#### Ejercicios
1. Accede al primer elemento de la segunda fila de un array 2D creado a partir de la siguiente lista: `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`.
2. Accede a los últimos tres elementos de un array 1D de la siguiente forma: `[1, 2, 3, 4, 5, 6, 7, 8, 9]`.
3. Crea un array 3D de tamaño `2x2x3` y accede al elemento de la primera fila, segunda columna y tercera capa.



In [16]:
v = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
elemento = v[1,0]
print(v)
print(elemento)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
40


In [17]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
v2 = v[-3:]
print(v2)

[7 8 9]


In [19]:
v = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print(v)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [20]:
print(v.shape)

(2, 5)


In [22]:
v[0,:].shape

(5,)

In [23]:
v[0,:3]

array([10, 20, 30])

In [25]:
v = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], range(5)])
print(v)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [  0   1   2   3   4]]


In [27]:
v[:2,-2:]

array([[ 40,  50],
       [ 90, 100]])

In [ ]:
np.array([1,2,3])

## 1. Acceso a los elementos de un array
- Para acceder a los elementos contenidos en un array se usan índices al igual que para acceder a los elementos de una lista, pero indicando los índices de cada dimensión separados por comas.

- Al igual que para listas, los índices de cada dimensión comienzan en 0.

- También es posible aplicar todas las operaciones de slicing e indexing.

In [28]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = array_2d[1, 2]  # Resultado: 6
print(element)

6


In [29]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
submatrix = array_2d[:2, :2]  # Resultado: [[1, 2], [4, 5]]
print(submatrix)

[[1 2]
 [4 5]]


In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0])  # Acceso al elemento de la fila 1 columna 0

print(a[1][0])  # Otra forma de acceder al mismo elemento

4
4


## 2. Operaciones matemáticas con arrays
Existen dos formas de realizar operaciones matemáticas con arrays: a nivel de elemento y a nivel de array.

- Las operaciones a nivel de elemento operan los elementos que ocupan la misma posición en dos arrays. Se necesitan, por tanto, dos arrays con las mismas dimensiones y el resultado es una array de la misma dimensión.

- Los operadores mamemáticos +, -, *, /, %, ** se utilizan para la realizar suma, resta, producto, cociente, resto y potencia a nivel de elemento.

- **Álgebra matricial**: Numpy incorpora funciones para realizar las principales operaciones algebraicas con vectores y matrices. La mayoría de los métodos algebráicos se agrupan en el submódulo linalg.

In [41]:
# 1. Suma entre Arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
result = array_1 + array_2  # Resultado: [5, 7, 9]
print(result)

[5 7 9]


In [42]:
array_1*array_2

array([ 4, 10, 18])

In [43]:
array_1.dot(array_2)

32

In [34]:
[1, 2, 3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [33]:
# 2. Multiplicación por un Escalar
array = np.array([1, 2, 3])
result = array * 3  # Resultado: [3, 6, 9]
print(result)

[3 6 9]


In [36]:
# 3. Producto elemento a elemento
array_1 = np.array([1, 2, 3])
array_2 = np.array([1, 2, 3, 4])
result = array_1*array_2  
print(result)


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [39]:
# 4. Diferencia con Listas
list_1 = [1, 2, 3, 'cara']
list_2 = [4, 5, 6, 7]
result = list_1 + list_2  # Esto no es una suma, sino concatenación 
print(result)

[1, 2, 3, 'cara', 4, 5, 6, 7]


In [40]:
# Suma de matrices
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
suma = matriz1 + matriz2
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


In [32]:
# Producto escalar de matrices
producto = matriz1.dot(matriz2)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


In [44]:
# Siempre podemos sumar o multiplicar escalares y matrices:
matriz1+2

array([[3, 4],
       [5, 6]])

In [45]:
# Division
print(matriz2/matriz1)

[[5.         3.        ]
 [2.33333333 2.        ]]


## 3. Creación de arrays
### Arrays con valores predefinidos:
- `a = np.empty(dimensiones)`: Crea un array vacío con las dimensiones especificadas.
- `a = np.zeros(dimensiones)`: Crea un array con las dimensiones especificadas, con elementos iguales a cero.
- `a = np.ones(dimensiones)`: Crea un array con las dimensiones especificadas, con elementos iguales a uno.
- `a = np.full(dimensiones, valor)`: Crea un array con las dimensiones especificadas, con todos los elementos iguales al valor proporcionado.
- `a = np.identity(n)`: Crea la matriz identidad de dimensión n.
- `a = np.eye(n)`: Crea una matriz identidad.

### Secuencias numéricas:
- `a = np.arange(inicio, fin, salto)`: Crea una secuencia de valores desde inicio hasta fin con un paso especificado.
- `a = np.linspace(inicio, fin, n)`: Crea una secuencia de n valores equidistantes entre inicio y fin.

### Arrays aleatorios:
- `a = np.random.random(dimensiones)`: Crea un array con las dimensiones especificadas, con elementos aleatorios entre 0 y 1.
- `a = np.random.rand(sample_size)`: Devuelve una muestra de números aleatorios distribuidos uniformemente entre 0 y 1.
- `a = np.random.randn(sample_size)`: Devuelve una muestra de números aleatorios con distribución normal.
- `a = np.random.randint(low, high, sample_size)`: Devuelve una muestra de números enteros dentro del rango especificado. low está inclído, high no.
- `a = np.random.choice(b, size=None, replace=True, p=None)`: Selecciona aleatoriamente elementos de un array `b`. `size` es el tamaño de la muestra que se va a seleccionar, `replace` es un booleano que indica si los valores se seleccionan con reemplazo o no. 

In [67]:
np.random.randint(5,10,(10,10))

array([[9, 6, 6, 7, 6, 6, 9, 9, 5, 5],
       [6, 7, 5, 6, 6, 5, 6, 8, 9, 6],
       [7, 5, 6, 7, 5, 5, 5, 7, 7, 5],
       [9, 6, 9, 5, 6, 6, 7, 6, 6, 8],
       [7, 5, 7, 9, 8, 8, 9, 8, 7, 8],
       [6, 7, 5, 6, 9, 6, 6, 8, 9, 8],
       [7, 7, 7, 5, 8, 6, 6, 5, 8, 5],
       [9, 7, 7, 7, 9, 7, 8, 5, 5, 9],
       [7, 9, 9, 9, 8, 5, 6, 5, 9, 8],
       [9, 9, 9, 7, 5, 8, 7, 6, 9, 6]])

In [73]:
# Crear una matriz de ceros:
m0 = np.zeros((3,3))
print(m0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
# Crear una matriz de unos:
d0 = 5
d1 = 2
dims = (5,2)
m1 = np.ones(dims)
print(m1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# Para utilizar valores complejos hay que definir el array como tipo complejo
dims = (3,6,2)
m0c = np.zeros(dims, dtype = complex)
print(m0c)

[[[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]]


In [10]:
m0b = np.zeros(5,dtype=bool)
print(m0b)

[False False False False False]


### Ejercicios
1. Crea un array 1D de 10 elementos inicializados a cero.
2. Crea una secuencia de valores desde 0 hasta 9 con un paso de 2.
3. Crea la matriz identidad en 2D con `N=4`.
4. Crea una matriz 2D de 3 filas y 4 columnas, con todos sus valores igual a 7.
5. Crea un array 1D que contenga 15 elementos distribuidos de manera uniforme entre 0 y 100.
6. Crea un array 1D con 10 valores distribuidos uniformemente, que vaya desde 0 hasta 50 (sin incluir 50).
7. Crea una matriz 3D de tamaño 2x2x2 con números aleatorios entre 0 y 1.
8. Crea un array 1D de 20 elementos con números enteros aleatorios entre 5 y 15.
9. Crea un array 2D de 5x5 con números aleatorios de una distribución normal con media 0 y desviación estándar 1.
10. Crea un array 1D con 30 números aleatorios y realiza la operación de suma entre este array y un array 1D de 30 números constantes (por ejemplo, todos 10). Asegúrate de que ambos arrays tengan la misma longitud.
11. Crea un array 1D de 10 elementos con números complejos, donde la parte real sea 2 y la parte imaginaria varíe entre 1 y 10.
12. Crea una matriz 2D de 3x3 con números complejos, donde la parte real sea generada aleatoriamente entre 1 y 5 y la parte imaginaria sea generada aleatoriamente entre 1 y 3.


In [103]:
areal = np.ones(10)*2
aim = 9*np.random.random(10)+1
acomp = areal + 1j*aim
print(acomp)

[2.+4.06207606j 2.+5.85406939j 2.+4.1661879j  2.+6.91482143j
 2.+5.03955734j 2.+5.12786454j 2.+2.31829536j 2.+7.61959179j
 2.+6.34458467j 2.+3.18886091j]


In [101]:
a1 = np.random.random(30)
a2 = 5*np.ones(30)
asuma = a1+a2
print(asuma)

[5.30342669 5.52491162 5.41100458 5.57715308 5.08028906 5.48227738
 5.84129077 5.33247978 5.90850301 5.3828734  5.21763983 5.92697205
 5.75967597 5.83264945 5.05305849 5.30258014 5.15236529 5.28970404
 5.35196343 5.64920743 5.26842895 5.28984653 5.73489555 5.95041349
 5.73551469 5.18386539 5.29277313 5.86413694 5.32678806 5.44387538]


In [97]:
ana = np.random.randn(5,5)
print(ana)
print(np.mean(ana))

[[-0.13015771  1.2816071  -0.60084642  0.61643445 -1.49293018]
 [-1.11910333 -1.10716017  0.15363964 -0.91987574 -0.0243396 ]
 [ 0.17020532  0.92277204  0.31722447  1.22895337  1.72045387]
 [-0.21665782 -1.18260242 -1.12796799  0.05213854 -0.21717955]
 [ 0.02725289  0.78377083 -1.04035519  0.36122325  0.65816682]]
-0.03541334171048174


In [78]:
# Ejercicio 1
alvaro = np.zeros(10)
print(alvaro)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [81]:
alvaro2 = np.arange(0,10,2)
print(alvaro2)

[0 2 4 6 8]


In [84]:
sergio = np.identity(4).astype(int)
print(sergio)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [85]:
sergio2 = np.full((3,4),7)
print(sergio2)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
np.ones((3,4))*7

In [86]:
irene = np.linspace(0,100,15)
print(irene)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


In [88]:
np.arange(0,100,100/14)

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        , 57.14285714, 64.28571429,
       71.42857143, 78.57142857, 85.71428571, 92.85714286])

In [91]:
irene2 = np.linspace(0,50,11)[:-1]
print(irene2)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [90]:
np.arange(0,50,50/10)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [93]:
elena = np.random.random((2,2,2))
print(elena)

[[[0.47244544 0.13768745]
  [0.17008025 0.40431912]]

 [[0.63017647 0.64139812]
  [0.90067061 0.93315669]]]


In [95]:
elena2 = np.random.randint(5,15,20)
print(elena2)

[ 8  9 14 13 13  8 11  6  5 11 14  7 10 13  9  5 11 12 10  6]


## 4. Filtrado de elementos de un array
- Una característica muy útil de los arrays es que es muy fácil obtener otro array con los elementos que cumplen una condición.

    `a[condicion]` : Devuelve una lista con los elementos del array a que cumplen la condición condicion.

In [106]:
a = np.arange(20)
print(a)
is_par = a%2==0
print(is_par)
apar = a[is_par]
print(apar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


In [107]:
apar = a[a%2==0]
print(apar)

[ 0  2  4  6  8 10 12 14 16 18]


In [108]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[a>3])

[4 5 6]


In [112]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
c1 = a%2==0
c2 = a>2
print(c1)
print(c2)

[[False  True False]
 [ True False  True]]
[[False False  True]
 [ True  True  True]]


In [113]:
np.logical_and(c1,c2)

array([[False, False, False],
       [ True, False,  True]])

In [114]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[(a % 2 == 0)]
print(b)
print( a[np.logical_and(a % 2 == 0, a > 2)] )


[2 4 6]
[4 6]


In [116]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])

arr > 1

array([False, False, False, False, False])

In [118]:
arr[arr>1]

array([], dtype=float64)

### Ejercicios:
1. Crea un array 1D `R1` con 100 elementos obtenidos de una distribución normal con media 2 y desviación estándar 1. ¿Cuál es la media y la desviación estándar de los valores obtenidos?
1. Selecciona aleatoriamente 5 elementos de `R1` sin reemplazo.
1. Filtra el array `R1` para obtener sólo los valores mayores que 0.
1. Crea un grid con 50 valores equidistantes entre 0 y 1.
1. Crea un array 1D de tamaño 10 con valores aleatorios enteros entre 1 y 10
1. Selecciona aleatoriamente con reemplazo 10 elementos de un array que incluya los números enteros entre 20 y 30, ambos inclusive.
1. Dado el array `a = np.array([1,3,6])`, crea una matriz `AD` cuya diagonal principal sea igual `a`, y los elementos fuera de la diagonal sean 0. 

In [148]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [149]:
a = np.array([1,3,6])
np.diag(a)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [146]:
v = np.arange(20,31)
v2 = np.random.choice(v,10)
print(v2)

[26 26 27 23 25 23 21 26 28 24]


In [145]:
x = np.linspace(0,1,50)
print(x)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [143]:
# Ej 2
R12 = np.random.choice(R1,5,False)
print(R12)

[1.92318743 1.35072608 2.47470349 1.38471614 3.59795135]


In [142]:
gridx = np.

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the ``choice`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``a`` can be selected mu

In [140]:
# Ej 1
R1 = np.random.randn(1000)+2
print(np.abs(2-np.mean(R1)))
print(np.std(R1))

0.009477355776243535
0.9951417225559559


## 5. Ejercicios 
Para resolver estos ejercicios, utiliza las funciones de creación de arrays que hemos visto arriba, operaciones aritméticas entre arrays, y bucles `for` o `if` cuando sea necesario. No utilices funciones o métodos de operaciones con arrays.

1. Dados dos arrays `a` y `b`, donde `a = np.array([1, 2, 3])` y `b = np.array([4, 5, 6])`, calcula la suma de los dos arrays.
1. Calcula el producto escalar de `a` y `b`.
1. Encuentra el valor medio de un array `v` con 10 valores aleatorios enteros entre 1 y 99 y sustituye todos los valores menores que la media por el valor máximo de `v`. 
1. Crea dos arrays `x` e `y` que incluyan respectivamente los números entre 1 y 4 (ambos inclusive) y entre 101 y 105 (ambos inclusive), y obtén un nuevo array `z` en el que cada elemento sea la suma de los cuadrados de los elementos correspondientes de `x` e `y`.
1. Dados `a = np.array([2, 5, 8])` y `b = np.array([3, 4, 7])`, crea un nuevo array que contenga `True` si el valor en `a` es mayor que el valor correspondiente en `b`, y `False` en caso contrario. Crea un nuevo array que concenga el mayor de cada pareja de valores.


## 6. Funciones básicas de Numpy

### Constantes matemáticas y físicas
- `np.pi`: Constante que representa el valor de π.
- `np.e`: Constante que representa la base del logaritmo natural, aproximadamente igual a 2.718.
- `np.inf`: Representa el infinito positivo.
- `np.nan`: Representa un valor nulo o no válido (Not a Number).

### Generación de mallas
- `np.arange(x0,xf,h)`: Genera una secuencia de números con separación `h`, desde `x0` hasta `xf`.
- `np.linspace(x0,xf,N)`: Genera una secuencia de `N` números equidistantes dentro del intervalo `[x0,xf]`.
- `np.meshgrid(x1,x2,...xn)`: Crea una malla de coordenadas a partir de arrays unidimensionales.


### Funciones matemáticas y estadísticas
- `np.mean(array, axis=None)`: Calcula la media de los elementos del array a lo largo del eje especificado. Por defecto, `axis=None` y se aplica a todos los elementos del array.
- `np.sum(array, axis=None)`: Calcula la suma de los elementos del array a lo largo del eje especificado.
- `np.min(array, axis=None)`: Encuentra el valor mínimo en el array a lo largo del eje especificado.
- `np.max(array, axis=None)`: Encuentra el valor máximo en el array a lo largo del eje especificado.
- `np.abs(array)`: Calcula el valor absoluto de cada elemento del array.
- `np.std(array, axis=None)`: Calcula la desviación estándar de los elementos del array a lo largo del eje especificado.
- `np.var(array, axis=None)`: Calcula la varianza de los elementos del array a lo largo del eje especificado.


### Funciones de álgebra lineal
- `np.linalg.det(a)`: Calcula el determinante de una matriz.
- `np.linalg.inv(a)`: Calcula la inversa de una matriz.
- `np.linalg.eigvals(a)`: Calcula los autovalores de una matriz.
- `np.linalg.solve(a, b)`: Resuelve un sistema de ecuaciones lineales, donde `a` es la matriz de coeficientes y `b` el término independiente.

### Funciones para ordenar y buscar elementos

- `np.sort(array, axis=-1)`: Ordena los elementos de un array a lo largo del eje especificado.
- `np.argsort(array, axis=-1)`: Devuelve los índices que ordenan los elementos de un array.
- `np.argmax(array, axis=None)`: Devuelve el índice del valor máximo en el array a lo largo del eje especificado.
- `np.argmin(array, axis=None)`: Devuelve el índice del valor mínimo en el array a lo largo del eje especificado.
- `np.where(bool array)`: Devuelve los índices de elementos que cumplen una condición dada.

### Funciones condicionales
- `np.isnan`: Devuelve un array booleano indicando los elementos que son `NaN` (Not a Number).
- `np.isfinite`: Devuelve un array booleano indicando los elementos finitos.
- `np.isinf`: Devuelve un array booleano indicando los elementos infinitos.


### Funciones lógicas
- `np.logical_and`: Realiza una operación lógica AND elemento a elemento en dos arreglos booleanos.
- `np.logical_or`: Realiza una operación lógica OR elemento a elemento en dos arreglos booleanos.
- `np.logical_not`: Realiza una operación lógica NOT elemento a elemento en un arreglo booleano.

### Funciones para tratar con índices

- `np.ravel_multi_index(multi_index, dims)`: Convierte un índice multidimensional en un índice lineal.
- `np.unravel_index(indices, shape)`: Convierte un índice lineal en un índice multidimensional.



### Funciones para Integración Numérica 

Las siguientes funciones calculan la integral numérica de una función `y`. Se pueden indicar también Las abcisas `x` o el paso `dx`, así como el eje de integración en el caso de arrays multidimencionales: 

- `numpy.trapz(y, x=None, dx=1, axis=-1)`: Regla del trapecio. 
- `numpy.simps(y, x=None, dx=1, axis=-1, even='avg')`: Regla de Simpson. `even` indica el método de tratamiento para un número par de puntos. (Opcional, por defecto 'avg').
- `numpy.cumsum(a, axis=None, dtype=None, out=None)`: Suma acumulativa. 
- `numpy.cumtrapz(y, x=None, dx=1, axis=-1, initial=None)`: Integral acumulativa con la regla del trapecio. `initial`: Valor inicial para la integral acumulativa. (Opcional)

### Funciones para calcular Histogramas

- `numpy.histogram(a, bins=10, range=None, weights=None, density=False)`: Calcula el histograma de una secuencia de datos. `bins` es un entero que define el número de intervalos o una secuencia indicando las abcisas de los intervalos (opcional, por defecto `bins=10`), `range` es el rango del bineado (opcional), `weights` los pesos asociados a cada valor de `a`, y `density` es un boleano, si es true el resultado es una distribución de probabilidad normalizada a 1 (opcional, por defecto `False`)

- `numpy.histogram2d(x, y, bins=10, range=None, density=False, weights=None)`: Calcula un histograma bidimensional.
- `numpy.histogramdd(sample, bins=10, range=None, density=False, weights=None)`: Calcula un histograma de n dimensiones.
- `numpy.bincount(x, weights=None, minlength=0)`: Cuenta la frecuencia de cada valor en un array de enteros no negativos.
    

## Métodos básicos de manipulación de arrays

### Propiedades de un array:

- `array.shape`: Devuelve la forma del array.
- `array.flatten()`: Devuelve una copia plana del array.
- `array.ndim`: Devuelve el número de dimensiones del array.
- `array.size`: Devuelve el número de elementos del array.
- `array.dtype`: Devuelve el tipo de datos del array.

### Operaciones sobre arrays:
- `array.T`: Devuelve la transpuesta del array.
- `array.trace()`: Calcula la suma de la diagonal del array.
- `array.reshape(new_shape)`: Cambia la forma del array.
- `array.copy()`: Devuelve una copia profunda del array.


In [150]:
# Ordenar elementos
x = np.random.randint(0,50,10)
print(x)
print(np.sort(x))
idx = np.argsort(x)
print(idx)

[46 39 23 37 47 18  0 46 36 22]
[ 0 18 22 23 36 37 39 46 46 47]
[6 5 9 2 8 3 1 0 7 4]


In [151]:
# Transposición de una matriz
transpuesta = matriz1.T
print("Matriz transpuesta:\n", transpuesta)

Matriz transpuesta:
 [[1 3]
 [2 4]]


In [153]:
# Traza
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

15


In [8]:
# Conversión de índices
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Convertir el índice (2, 3) a un índice 1D
indice_2D = (2, 3)
indice_1D = np.ravel_multi_index(indice_2D, matriz.shape)
print("Índice 2D (fila, columna):", indice_2D)
print("Índice 1D:", indice_1D)
print(matriz[2,3])
print(matriz.flatten()[11])

Índice 2D (fila, columna): (2, 3)
Índice 1D: 11
12
12


In [9]:
# Conversión de índices
# Convertir el índice 9 a un par de índices 2D
indice_1D = 9
indice_2D = np.unravel_index(indice_1D, matriz.shape)
print("Índice 1D:", indice_1D)
print("Índice 2D (fila, columna):", indice_2D)

Índice 1D: 9
Índice 2D (fila, columna): (2, 1)


In [49]:
# Argmax en 2 y 3 dimensiones
matriz_2D = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Obtener el índice del valor máximo en toda la matriz
indice_maximo = np.argmax(matriz_2D)
print("Índice del valor máximo en la matriz 2D:", indice_maximo)

# Crear una matriz 3D de ejemplo
matriz_3D = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])

# Obtener el índice del valor máximo a lo largo del eje especificado (eje 2)
indice_maximo_3D = np.argmax(matriz_3D, axis=2)
print("Índice del valor máximo a lo largo del eje 2 en la matriz 3D:", indice_maximo_3D)

Índice del valor máximo en la matriz 2D: 8
Índice del valor máximo a lo largo del eje 2 en la matriz 3D: [[2 2]
 [2 2]]


In [154]:
# Resolución de sistemas de ecuaciones
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))



[-1.  1.]


### Ejercicios
 
1. Crea un array de tamaño 10 con valores aleatorios entre 0 y 1. Luego, calcula la media, la suma, el valor mínimo y el valor máximo de los elementos del array.
1. Dada la matriz `A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, calcula su determinante, su traza, y la matriz inversa. ¿Cuál es el resultado de multiplar la matriz por la inversa?
1. Dados dos arrays `x` y `y`, donde `x` es un grid de 5 puntos de 0 a 2, e `y` los números del 0 al 4, calcula el producto producto escalar de ambos.
1. Crea un array con los valores de la función seno para ángulos entre 0 y 2π con incrementos de 0.1.
1. Dada la matriz `B = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])`, ordena los elementos de cada fila de manera ascendente.
1. Dado el array `z = np.array([1, 2, 3, np.nan, 5, np.inf, 7])`, encuentra los índices de los elementos que son finitos.
1. Crea un array aleatorio con 10 valores distribuidos uniformemente entre -1 y 2. Encuentra los índices de los valores entre 0 y 1. 
1. Resuelve el sistema de ecuaciones lineales Ax = b, donde A es la matriz de coeficientes y b es el vector de términos independientes. Utiliza las siguientes matrices y vectores: `A = np.array([[2, 3], [1, 4]])`, `b = np.array([5, 6])`.

    


In [179]:
x = np.random.random(10)*3-1
print(x)
indices = np.where(np.logical_and(x>0, x<1))
print(indices)

[ 1.75054204  1.85872582  0.80560739 -0.89792932 -0.17681298 -0.85307382
  1.37734215 -0.27988755  1.55388928 -0.87133169]
(array([2], dtype=int64),)


In [177]:
z = np.array([1, 2, 3, np.nan, 5, np.inf, 7])
print(np.where(np.isfinite(z)))
print(np.where(~np.isfinite(z)))
print(np.where(np.logical_not(np.isfinite(z))))

(array([0, 1, 2, 4, 6], dtype=int64),)
(array([3, 5], dtype=int64),)
(array([3, 5], dtype=int64),)


In [173]:
B = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
B_ord = np.sort(B)
print(B_ord)

[[1 3 4]
 [1 5 9]
 [2 5 6]]


In [155]:
import numpy aººººº

In [158]:
a = np.random.randint(0,10,(3,2))
print(a)

[[9 8]
 [4 9]
 [2 0]]


In [159]:
np.max(a)

9

In [160]:
np.max(a, axis=0)

array([9, 9])

In [161]:
np.max(a, axis=1)

array([9, 9, 2])

### Más ejercicios...
1. Crea una matriz de tamaño 5x4 con valores aleatorios enteros entre 0 y 10. Luego, encuentra los índices del valor máximo en cada fila de la matriz.
1. Encuentra el valor medio de un array `v` con 10 valores aleatorios enteros entre 1 y 99, y sustituye todos los valores menores que la media por el valor máximo de `v`.     
1. Calcula la integral numérica de una función x<sup>2</sup> en el invervalo [0,1] utilizando el método del trapecio. ¿Cómo cambia el resultado con el número de puntos utilizados para integrar?
1. Genera dos nubes de N puntos aleatorios cada una, dados por sendas distribuciones Gausianas con media 0 y desviaciones estándar 1 y 3. Crea una tercera variable aleatoria que es la suma de las dos primeras. Calcula el histograma de la distribución de puntos resultante. ¿Cuál es la media y la desviación estándar de la distribución resultante? ¿Y si la media de la seguda distribución es igual a 1?

In [193]:
N = 1000
p1 = np.random.randn(N)
p2 = np.random.randn(N)*3

suma = p1+p2
media = np.mean(suma)
desv = np.std(suma)

print(media, desv)



0.09862608214953988 3.057278465089565


In [180]:
v = np.random.randint(1,100,10)
vmean = np.mean(v)
vmax = np.max(v)

print(v, vmean, vmax)
#nuevo_v = np.zeros_like(v) #np.zeros(10)
nuevo_v = v.copy()
for i in range(len(v)):
    if v[i]<vmean:
        nuevo_v[i] = vmax
#    else:
#        nuevo_v[i] = v[i]

print(nuevo_v)



[36 66 46 86 48 54 40 19 88 38] 52.1 88
[88 66 88 86 88 54 88 88 88 88]


In [184]:
indices = np.where(v<vmean)
print(indices)
nuevo_v2 = v.copy()
nuevo_v2[indices] = vmax
print(nuevo_v2)
print(np.all(nuevo_v == nuevo_v2))

(array([0, 2, 4, 6, 7, 9], dtype=int64),)
[88 66 88 86 88 54 88 88 88 88]
True


In [186]:
nuevo_v3 = v.copy()
nuevo_v3[nuevo_v3<vmean] = vmax
print(nuevo_v3)

[88 66 88 86 88 54 88 88 88 88]


In [167]:
np.max(a, axis=1)

array([9, 9, 7, 8, 8])

In [163]:
# Ejercicio 1
a = np.random.randint(0,11,(5,4))
print(a)
maximos = np.max(a, axis = 1)
print(maximos)

[[2 9 9 9]
 [0 0 9 0]
 [7 1 5 4]
 [8 8 1 4]
 [8 5 8 2]]
[9 9 7 8 8]


In [172]:
indices = np.argmax(a, axis=1)
print(indices)
indices2d = np.array([np.array([i, indices[i]]) for i in range(5)])
print(indices2d)

[1 2 0 0 0]
[[0 1]
 [1 2]
 [2 0]
 [3 0]
 [4 0]]


In [169]:
indices = np.argmax(a, axis=1, keepdims=True)
print(indices)
print(indices.shape)

[[1]
 [2]
 [0]
 [0]
 [0]]
(5, 1)


## 7. Ejercicios finales

1. Calcula el movimiento de un proyectil de masa 2kg que es lanzado desde el suelo a 20m/s con un ángulo de 45º. ¿Cuál es la altura máxima que alcanza? ¿A qué distancia de la posición inicial impacta con el suelo? Utiliza el método de Euler para integrar numéricamente.
1. Simula el movimiento de un péndulo simple utilizando ecuaciones diferenciales.
1. Calcula el valor de pi utilizando un Método Monte Carlo. Para ello, tendremos en cuenta que el área de un cuadrado de lado 2r es 4r^2, mientras que el área del círculo inscrito en él es pi r^2. Para estimar el área de forma numérica sin conocer el valor de pi, generaremos N puntos en el plano de forma aleatoria, contenidos en un cuadrado centrado en el origen y cuyo lado mide 2 unidades. La relación entre las áreas del cuadrado y del círculo es la misma que la relación entre el número total de puntos generados y aquellos que caen dentro del círculo. A partir de esta relación estimamos el valor de pi. ¿Cómo depende la estimación con N? Si generas varios resultados con el mismo N, ¿cuál es la variabilidad? ¿Cómo están distribuidos los números resultantes?